CREATE TABLE value_of_care (

facility_id INT,
facility_name TEXT,
address VARCHAR,
city VARCHAR,
state VARCHAR, 
zip_code INT,
payment_measure_id VARCHAR,
payment_measure_name VARCHAR,
payment_category VARCHAR,
denominator INT,
payment INT, 
lower_estimate INT,
higher_estimate INT, 
value_of_care_display_id VARCHAR,
value_of_care_display_name VARCHAR, 
value_of_care_category VARCHAR, 
start_date DATE,
end_date DATE, 
population INT,
poverty_rate DECIMAL,
caucasian_% DECIMAL,
african_american_% DECIMAL,
american_indian_% DECIMAL,
asian_% DECIMAL,
native_hawaiian_% DECIMAL,
two_or_more_races_% DECIMAL, 
hispanic_% DECIMAL
);
